export default {
  REQUEST_USER_FEED: 'Request user feed',
  REQUEST_CURRENT_USER: 'Request current user',
  RECEIVE_CURRENT_USER: 'Receive current user',
  BANNER_TOGGLE_PREV: 'toggle previous banner',
  BANNER_TOGGLE_NEXT: 'toggle next banner',
  FETCH_CONFIG_DATA: 'Fetch config data',
  RECEIVE_CONFIG_DATA_SUCCESS: 'Config data received',
  RECEIVE_CONFIG_DATA_ERROR: 'Config data receipt failed',
  FETCH_APP_DATA: 'Fetch app data',
  FETCH_SEARCH_SUGGESTIONS: 'Fetch search suggestions',
  RECEIVE_SEARCH_SUGGESTIONS: 'Receive search suggestions',
  FETCH_USER_FEED: 'Fetch user feed',
  FETCH_USER_FEED_SUCCESS: 'Fetch user feed succeful',
  FETCH_USER_FEED_ERROR: 'Fetch user feed failed',
  USER_AVATAR_PLACEHOLDER: 'http://localhost:8080/images/avatar_small.png',
  FEED_IMAGE_PLACEHOLDERS: [
    'http://localhost:8080/images/feed1.jpg',
    'http://localhost:8080/images/feed2.jpg',
    'http://localhost:8080/images/feed3.jpg',
    'http://localhost:8080/images/feed4.jpg',
  ],
  LIKE_DEFAULT_IMG_URL: 'http://localhost:8080/images/avatar_small.png',
  API_BASE_URL: 'http://tilte-api.herokuapp.com/api',
};
